# File meant to create an image
# that can be used in the development environment

FROM node:12.2.0-alpine

WORKDIR '/app'

COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

CMD ["yarn", "start"]